blank_issues_enabled: false
contact_links:
  - name: Telegram Audio Downloader Dokumentation
    url: https://elpablo777.github.io/Telegram-Audio-Downloader/
    about: Hier findest du die offizielle Dokumentation
  - name: E-Mail Support
    url: mailto:hannover84@msn.com
    about: Kontaktiere uns per E-Mail für Support-Anfragen
  - name: 💬 Discussions
    url: https://github.com/Elpablo777/Telegram-Audio-Downloader/discussions
    about: Community-Diskussionen und Fragen
  - name: 🌐 Project Website
    url: https://elpablo777.github.io/Telegram-Audio-Downloader/
    about: Offizielle Projekt-Website
  - name: 📧 Direct Contact
    url: mailto:hannover84@msn.com
    about: Direkte Kontaktaufnahme für spezielle Anfragen