name: 🚀 CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run weekly security scans
    - cron: '0 2 * * 1'

env:
  PYTHONUNBUFFERED: 1
  PYTHONDONTWRITEBYTECODE: 1

jobs:
  test:
    name: 🧪 Tests & Code Quality
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.11', '3.12', '3.13']
        exclude:
          # Temporarily exclude Python 3.13 on Windows due to compatibility
          - os: windows-latest
            python-version: '3.13'

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4

    - name: 🐍 Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        allow-prereleases: true

    - name: 📦 Cache Dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cache/pip
          ~/.local/share/pip-cache
          ${{ runner.os == 'Windows' && '~\\AppData\\Local\\pip\\Cache' || '' }}
          ${{ runner.os == 'macOS' && '~/Library/Caches/pip' || '' }}
        key: ${{ runner.os }}-pip-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt', '**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-${{ matrix.python-version }}-
          ${{ runner.os }}-pip-

    - name: 🔧 Install Core Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip install pytest pytest-cov pytest-asyncio pytest-mock
        pip install flake8 mypy
        pip install coverage[toml]

    - name: 📦 Install Project Dependencies
      run: |
        # Install only core requirements (skip dev dependencies)
        python -c "
        import re
        with open('requirements.txt', 'r') as f:
            lines = f.readlines()
        core_deps = []
        for line in lines:
            line = line.strip()
            if line and not line.startswith('#'):
                # Skip dev dependencies
                if not any(dev in line.lower() for dev in ['pytest', 'black', 'isort', 'flake8', 'mypy', 'docker']):
                    core_deps.append(line)
        with open('core_requirements.txt', 'w') as f:
            f.write('\n'.join(core_deps))
        "
        pip install -r core_requirements.txt
        
        # Install package in development mode
        pip install -e .

    - name: 🎯 Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=build,dist,*.egg-info
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --exclude=build,dist,*.egg-info

    - name: 🧪 Run Basic Tests
      run: |
        # Create minimal test if tests directory doesn't exist
        if [ ! -d "tests" ]; then
          mkdir -p tests
          cat > tests/test_basic.py << 'EOF'
import pytest
import sys
import os

# Add src to path
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

def test_import():
    """Test that the package can be imported."""
    try:
        import telegram_audio_downloader
        assert hasattr(telegram_audio_downloader, '__version__')
        print(f"✅ Package version: {telegram_audio_downloader.__version__}")
    except ImportError as e:
        pytest.fail(f"Could not import package: {e}")

def test_version():
    """Test version format."""
    import telegram_audio_downloader
    version = telegram_audio_downloader.__version__
    import re
    assert re.match(r'^\d+\.\d+\.\d+', version), f"Invalid version format: {version}"

def test_basic_utils():
    """Test basic utility functions if available."""
    try:
        from telegram_audio_downloader.utils import sanitize_filename, format_file_size
        # Test sanitize_filename
        result = sanitize_filename("Test (File) [Name] {2024}.mp3")
        assert isinstance(result, str)
        assert "(" not in result  # Should be sanitized
        
        # Test format_file_size  
        result = format_file_size(1024)
        assert isinstance(result, str)
        assert "KB" in result or "B" in result
        print("✅ Utils functions work correctly")
    except ImportError:
        print("⚠️ Utils not available yet - skipping utils test")
        pass
EOF
        fi
        
        # Run tests with pytest
        python -m pytest tests/ -v --tb=short -x
      continue-on-error: false

    - name: 🧪 Run Package Verification
      run: |
        # Test CLI help if available
        python -c "
        try:
            from telegram_audio_downloader.cli import main
            print('✅ CLI module imports successfully')
        except ImportError as e:
            print(f'⚠️ CLI not available yet: {e}')
        
        try:
            import telegram_audio_downloader
            print(f'✅ Package imported successfully, version: {telegram_audio_downloader.__version__}')
        except Exception as e:
            print(f'❌ Package import failed: {e}')
            exit(1)
        "

    - name: 🔍 Basic Type Checking
      run: |
        # Only run mypy on existing Python files
        if [ -d "src/telegram_audio_downloader" ]; then
          python -m mypy src/telegram_audio_downloader/__init__.py --ignore-missing-imports --no-strict-optional
        else
          echo "⚠️ Source directory not found, skipping type check"
        fi
      continue-on-error: true

    - name: 📊 Upload Test Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-${{ matrix.os }}-${{ matrix.python-version }}
        path: |
          tests/
        retention-days: 7

  docker:
    name: 🐳 Docker Build Test
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4

    - name: 🏗️ Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: 🐳 Test Docker Build
      run: |
        # Create minimal Dockerfile if it doesn't exist
        if [ ! -f "Dockerfile" ]; then
          cat > Dockerfile << 'EOF'
FROM python:3.11-slim

WORKDIR /app

# Copy requirements first for better caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy source code
COPY . .

# Install package
RUN pip install -e .

# Default command
CMD ["python", "-c", "import telegram_audio_downloader; print('✅ Docker image works!')"]
EOF
        fi
        
        # Build Docker image
        docker build -t telegram-audio-downloader:test .
        
        # Test image
        docker run --rm telegram-audio-downloader:test

  security:
    name: 🔒 Basic Security Checks
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: 📥 Checkout Code
      uses: actions/checkout@v4

    - name: 🐍 Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: 🔍 Install Security Tools
      run: |
        pip install bandit safety

    - name: 🛡️ Run Security Scan
      run: |
        # Run bandit on source code if available
        if [ -d "src" ]; then
          bandit -r src/ -f json -o bandit-report.json || true
          echo "Bandit scan completed"
        fi
        
        # Run safety check on requirements
        safety check --json || true
        echo "Safety check completed"
      continue-on-error: true

    - name: 📊 Upload Security Report
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: security-reports
        path: |
          bandit-report.json
        retention-days: 7

  notify:
    name: 📢 CI Results
    runs-on: ubuntu-latest
    needs: [test, docker, security]
    if: always()

    steps:
    - name: 📊 Report Status
      run: |
        echo "## 📊 CI/CD Pipeline Results" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ needs.test.result }}" = "success" ]; then
          echo "✅ **Tests**: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Tests**: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.docker.result }}" = "success" ]; then
          echo "✅ **Docker**: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "❌ **Docker**: Failed" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ "${{ needs.security.result }}" = "success" ]; then
          echo "✅ **Security**: Passed" >> $GITHUB_STEP_SUMMARY
        else
          echo "⚠️ **Security**: Issues detected" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "For detailed results, check the individual job logs above." >> $GITHUB_STEP_SUMMARY
        
        # Fail if critical jobs failed
        if [ "${{ needs.test.result }}" != "success" ]; then
          echo "❌ Critical tests failed!"
          exit 1
        else
          echo "✅ All critical checks passed!"
        fi